### ISSUE TITLE
想在AOT环境下使用

### ISSUE THREAD

**Issue by 44578287** [XFEstudio/XFEExtension.NetCore.AutoConfig#1]
由于一些特殊需求我需要以AOT模式开发，但是AOT他会禁用反射 具体报错如下
System.InvalidOperationException:“Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.”
希望能够适配

**Comment by XFEstudio** [comment]
收到反馈，已提上开发日程

**Comment by XFEstudio** [comment]
目前，你可以向项目中添加
```xml
<PropertyGroup>
  <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
</PropertyGroup>
```
来暂时解决问题，具体可以参考：
直接使用Json：[Json变更](https://learn.microsoft.com/zh-cn/dotnet/core/compatibility/serialization/8.0/publishtrimmed?source=recommendations)
以及使用源生成：[在System.Text.Json中使用源生成](https://learn.microsoft.com/zh-cn/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-8-0)

**Comment by XFEstudio** [comment]
现在已经支持了AOT适配

**Comment by 44578287** [comment]
老哥更新完完全跑不了了，clone项目跑里面的Test也跑不起来
例如Test里的Console.WriteLine($"上一次读取的值是：{UserProfile.UserInfoList.ToJson()}");
报错
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	CS0117	“UserProfile”未包含“UserInfoList”的定义	AutoConfig.Analyzer.Test	D:\Code\DotNet\XFEExtension.NetCore.AutoConfig\AutoConfig.Analyzer.Test\Program.cs	23	

目前包版本2.0.4 在NuGet上下的包

**Comment by XFEstudio** [comment]
@44578287 clone项目是跑不起来是Github上面还没有同步，现在更新了，应该可以了
2.0以上版本和1.0版本有本质上的差别，支持AOT 导致原本的一些方法被弃用

**Comment by XFEstudio** [comment]
如果对你的项目有很大的影响可以先继续使用1.0版本的最后一个版本，2.0改动较大
